require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/v1/agentes", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Agente. As you add validations to Agente, be sure to
  # adjust the attributes here as well.
  

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # AgentesController, or in your router and rack
  # middleware. Be sure to keep this updated too.

  let!(:agentes_list) do
    FactoryBot.create_list(:agente, 10)
  end
  let!(:agentes_url) { '/v1/agentes' }
  describe "GET /index" do
    
    it "renders a successful response to all agents" do
      get agentes_url
      expect(json).not_to be_empty
      expect(json.size).to eq(10)
      expect(response).to be_successful
    end
  end

  describe "GET /show" do

    it "renders a successful response to a single agent id" do
      agente = agentes_list.first
      get "/v1/agentes/#{agente.id}"
      expect(json).not_to be_empty
      expect(response).to be_successful
      expect(json['nombre']).to eq('Nombre del agente')
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Agente" do
        byebug       
        expect {
          post '/v1/agentes',
               params: { agente: attributes_for(:agente) }
        }.to change(Agente, :count).by(1)
      
       
      end

      it "renders a JSON response with the new agente" do
        post '/v1/agentes', params: { agente: attributes_for(:agente) }
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Agente" do
       
        expect {
          post '/v1/agentes',
               params: { agente: {invalid_param: "invalid"} }
        }.to change(Agente, :count).by(0)
      end

      it "renders a JSON response with errors for the new agente" do
        post agentes_url,
        params: { agente: {invalid_param: "invalid"} }
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let!(:update_agente){ FactoryBot.create(:agente)}
      let!(:new_attributes) {
        {
          id: update_agente.id,
          nombre: "Nombre actualizado"
        }
      }

      it "updates the requested agente" do
     
        patch agentes_url + "/#{update_agente.id}", params: { agente: new_attributes }
       
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including("application/json"))
        
      end

      it "renders a JSON response with the agente" do
    
         patch agentes_url + "/#{new_attributes[:id]}",
       
              params: { agente: new_attributes }
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the agente" do
        error_agente =  FactoryBot.create(:agente)
        patch agentes_url + "/#{error_agente.id}",
              params: { agente: {nombre: ""} }
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested agente" do
    
      delete_agente =  FactoryBot.create(:agente)
      expect {
       
        delete agentes_url + "/#{delete_agente.id}"
      }.to change(Agente, :count).by(-1)
    end
  end
end
